
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    namespace: test-zone
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 1.5.1
    helm:
      releaseName: homepage
      valuesObject:
        image:
          repository: ghcr.io/gethomepage/homepage
          tag: v0.8.11
        env:
          TZ: America/New_York
        service:
          main:
            ports:
              http:
                port: 3000
        persistence:
          config:
            enabled: true
            mountPath: /app/config
            size: 1Gi
        addons:
          codeserver:
             enabled: true
             volumeMounts:
               - name: config
                 mountPath: /app/config
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: test-zone
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: test-zone
spec:
  ingressClassName: ingress-nginx-internal
  rules:
    - host: auth.<path:stringreplacesecret#domain>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homepage
  namespace: test-zone
spec:
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  - name: external
    namespace: gateway
    sectionName: https
  hostnames:
  - "homepage.<path:stringreplacesecret#domain>"
  rules:
  - backendRefs:
    - name: homepage
      port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: homepage
  annotations:
    external-dns.custom/type: private
spec:
  endpoints:
    - dnsName: homepage.<path:stringreplacesecret#domain>
      recordType: CNAME
      targets:
        - ingress.<path:stringreplacesecret#domain>
      # targets:
      #   - intgw.<path:stringreplacesecret#domain>
      # providerSpecific:
      #   - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
      #     value: "false"