---
kind: Namespace
apiVersion: v1
metadata:
  name: test-zone
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest
  namespace: argocd
spec:
  destination:
    namespace: test-zone
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template 
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 1.5.1
    helm:
      releaseName: speedtest
      valuesObject:
        image:
          repository: docker.io/openspeedtest/latest
          tag: 2.17.01

        service:
          main:
            ports:
              http:
                port: 3000
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
