
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speedtest
  namespace: argocd
spec:
  destination:
    namespace: test-zone
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 2.6.0
    helm:
      values:
        app-template:
          controllers:
            main:
              containers:
                main:
                  image:
                    repository: docker.io/openspeedtest
                    tag: latest
          service:
            main:
              ports:
                http:
                  port: 3000
                  protocol: HTTP
          ingress:
            main:
              enabled: true
              className: nginx
              annotations:
                nginx.ingress.kubernetes.io/proxy-body-size: 50m
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - host: &host speedtest.vanillax.me
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - hosts:
                    - *host
                  secretName: speedtest-tls-certificate
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
